packetbeat.interfaces.device: any

packetbeat.flows:
  timeout: 30s
  period: 10s

packetbeat.protocols:
  - type: icmp
    enabled: true

#  - type: dns
#    ports: [53]

  - type: http
    ports: [80, 8080]

#  - type: amqp
#    ports: [5672]
#
#  - type: cassandra
#    ports: [9042]
#
#  - type: memcache
#    ports: [11211]
#
#  - type: mysql
#    ports: [3306]

  - type: redis
    ports: [6379]

#  - type: pgsql
#    ports: [5432]
#
#  - type: thrift
#    ports: [9090]
#
#  - type: tls
#    ports: [443]

packetbeat.procs:
  enabled: true
  monitored:
#    - process: mysqld
#      cmdline_grep: mysqld
#
#    - process: pgsql
#      cmdline_grep: postgres

    - process: nginx
      cmdline_grep: nginx
#
#    - process: app
#      cmdline_grep: gunicorn

fields_under_root: true

fields:
  app: "gateway"

tags: ["packetbeat", "gateway"]

processors:
  - add_cloud_metadata:

output.redis:
  hosts: ["104.248.244.33"]
  #  password: null
  key: "packetbeat"
  db: 0
  timeout: 5